---
title: "COVID-19"
author: "Daniel"
date: "25/3/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse) # Data manipulation
library(lubridate) # Dates parsing
library(gganimate) # Plot animations
library(RSocrata)  # Sources from the government
library(grid)      # Plotting
library(gghighlight)
library(ggforce)
library(plotly)
library(ggpmisc)
library(readxl)
library(zoo)
library(writexl)
library(ggrepel)
theme_set(theme_bw())
```

## Data reading and manipulation

```{r}
raw_data <- read.socrata("https://www.datos.gov.co/resource/gt2j-8ykr.csv") %>% 
  as_tibble()

antioquia_model <- read_csv("../src/model_data_v2.csv")

covid <- raw_data %>% 
  mutate_at(vars(starts_with("fecha")), as_date)

cumulative <- covid %>%
  group_by(fecha_diagnostico, departamento) %>%
  summarize(n = n()) %>%
  group_by(departamento) %>% 
  mutate(acum = cumsum(n)) %>% 
  ungroup()
```

## National cases

```{r}
national_cases <- cumulative %>%
  filter(departamento %in% c("Antioquia", "Meta", "Cartagena D.T. y C.", "Valle del Cauca", "Bogotá D.C.")) %>% 
  ggplot(aes(x = fecha_diagnostico, y = acum, color = departamento)) +
  geom_line(size = 0.5) +
  geom_point(size = 0.6) +
  geom_vline(xintercept = as.numeric(ymd("2020-03-24")), linetype = 4, color = "black") +
  scale_x_date(date_breaks = "10 days", date_labels = "%d %b") +
  scale_y_continuous(breaks = seq(from = 0, to = 6000, by = 200)) +
  stat_peaks(aes(color = departamento, 
                 label = paste(..y.label..)), 
             geom = "text_repel",
             vjust = 1,
             span = NULL,
             y.label.fmt = "%.0f infectados",
             size = 2) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        title = element_text(size = 16, face = "bold", family = "sans"),
        legend.text = element_text(margin = margin(r = 10, unit = "pt"), size = 6),
        plot.title = element_text(hjust = 0.5, size = 10),
        plot.subtitle = element_text(size = 6)) +
  labs(title = "COVID-19: Evolución de casos acumulados por departamento",
       subtitle = "Fuente: Instituto Nacional de Salud (12/05/2020)",
       x = NULL,
       y = NULL,
       color = NULL)

# Animation
dpts_anim <- national_cases +
  transition_reveal(fecha_diagnostico)
gganimate::animate(dpts_anim, height = 1000, width = 1600)
gganimate::anim_save("dpts_animation.gif")

# Highlight
dpts_high <- national_cases +
  gghighlight(departamento == "Antioquia")
ggsave(plot = dpts_high, "../plots/dpts_highlight_25-04-2020.png", width = 11, height = 6)  
#Static
ggsave(plot = national_cases, "../plots/dpts_18-05-2020.png", width = 8, height = 6)
```


## Model performance

```{r}
antioquia <- cumulative %>% 
  filter(departamento == "Antioquia",
         acum > 200)

colors <- c("acum" = "black", "infectionsS1" = "darkblue", "infectionsS2" ="darkorange", "infectionsS3" = "darkred", "infectionsS4" = "aquamarine4", "n" = "grey")

tidy_antioquia <- antioquia_model %>%
  mutate(fecha_diagnostico = seq.Date(from = ymd("2020-04-07"), to = ymd("2021-04-07"), by = 1)) %>% 
  left_join(antioquia, by = "fecha_diagnostico") %>% 
  pivot_longer(cols = c("infectionsS1", "infectionsS2", "infectionsS3", "infectionsS4", "n", "acum"))

models_plot <- tidy_antioquia %>% 
  mutate(fecha_diagnostico = as_datetime(fecha_diagnostico)) %>%
  filter(name != "n") %>% 
  ggplot(aes(fecha_diagnostico, value, color = name)) +
  geom_line() +
  geom_point(size = 0.9, alpha = 0.4) +
  scale_color_manual(values = colors, labels = c("Casos confirmados", 
                                                 "Escenario pesimista (30%)", 
                                                 "Escenario intermedio (45%)",
                                                 "Escenario optimista (60%)",
                                                 "Escenario ajustado (56%)")) +
  facet_zoom(xlim = c(ymd_hms("2020-04-15 00:00:00"), ymd_hms("2020-05-30 00:00:00")),
             ylim = c(0, 1000), zoom.size = 1.2) +
  stat_peaks(aes(color = name, 
                 label = paste(..y.label.., ..x.label..)), 
             geom = "text", 
             vjust = -0.5,
             hjust = 0.5,
             span = NULL,
             x.label.fmt = "%d-%m(%b)",
             y.label.fmt = "%.0f infectados") +
  theme(axis.text.y = element_text(size = 14),
        title = element_text(size = 16, face = "bold", family = "sans"),
        legend.position = "bottom",
        legend.text = element_text(margin = margin(r = 40, unit = "pt")),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size = 10)
        ) +
  labs(title = "COVID-19: Antioquia - Modelo SIR - Población susceptible: 6.355.502",
       subtitle = "Fuente casos confirmados: Instituto Nacional de Salud (17/05/2020)",
       x = NULL,
       y = NULL,
       color = NULL) 

# Animation
antioquia_anim <- models_plot +
  transition_reveal(fecha_diagnostico)
gganimate::animate(antioquia_anim, height = 800, width = 1600)
gganimate::anim_save("models_plot.gif")


#Static
ggsave(plot = models_plot, "../plots/model_comparison_18-05-2020.png", width = 13, height = 6)
```

## Example of why time series should not be used

```{r}
library(tsibble)
library(fable)
ts_data <- cumulative %>% 
  group_by(fecha_diagnostico) %>% 
  summarize(acumulado = sum(acum)) %>%
  as_tsibble() %>%
  tsibble::fill_gaps() %>%
  mutate(acumulado = zoo::na.locf(acumulado, fromLast = TRUE)) 

ts_data %>% 
  model(ets = fable::ETS(acumulado),
        arima = ARIMA(acumulado),
        linear = fable::TSLM(acumulado ~trend() + season())) %>% 
  forecast(h = "15 days") %>% 
  autoplot(filter(ts_data,  fecha_diagnostico > ymd("2020-03-01")), level = NULL)
  
```

## Local data for validation

```{r}
# This function joins the data with the real information, needs to be modified once we get UCI and UCE
get_mixed <- function(raw_data, ips_data) {
  raw_data %>%
  mutate(date = seq.Date(from = ymd("2020-03-25"), to = ymd("2021-03-11"), by = 1)) %>% 
  left_join(ips_data, by = c("date" = "Fecha consulta")) %>%
  mutate(n = replace_na(n,0),
         acum = cumsum(n)) %>% 
  mutate(n = case_when(date > Sys.Date() ~ NA_real_,
                       TRUE ~ n),
         acum = case_when(date > Sys.Date() ~ NA_real_,
                          TRUE ~ acum))
}
```


### Hospitalization

```{r}
raw_ips <- read_excel("../src/BASE DE DATOS COVID-19 29-04-20.xlsx", skip = 6) %>% 
  mutate(tipo_cama = case_when(str_detect(Servicio, "MI") ~ "hospitalizacion",
                               str_detect(Servicio, "UCI") ~ "UCI",
                               str_detect(Servicio, "PISO") ~ "hospitalizacion",
                               str_detect(Servicio, "UCE") ~ "UCE",
                               str_detect(Servicio, "SAI") ~ "hospitalizacion",
                               str_detect(Servicio, "OBSERVACION") ~ "hospitalizacion",
                               TRUE ~ "ambulatorio"))
hosp_data <- read_csv("../src/hosp_data.csv")
new_hosp_data <- read_csv("../src/new_hosp_data.csv")


ips_hosp <- raw_ips %>%
  filter(Resultado...63 == "Positivo",
         tipo_cama == "hospitalizacion") %>% 
  mutate(`Fecha consulta` = as_date(`Fecha consulta`)) %>% 
  group_by(`Fecha consulta`, ERP) %>%
  count() %>%
  ungroup()

get_mixed(new_hosp_data, ips_hosp)
hosp_mixed <- get_mixed(new_hosp_data, ips_hosp)

tidy_hosp <- hosp_mixed %>% 
  pivot_longer(cols = c("hospS1", "hospS2", "hospS3", "hospS4", "acum"))


hosp_colors <- c("acum" = "black", "hospS1" = "darkblue", "hospS2" = "darkorange", "hospS3" = "darkred", "hospS4" = "aquamarine4")
hosp_alpha <- c("acum" = 1, "hospS1" = 0.4, "hospS2" = 0.4, "hospS3" = 0.4, "hospS4" = 1)

hosp_plot <- tidy_hosp %>%
  mutate(date = as_datetime(date)) %>% 
  ggplot(aes(date, value, color = name, alpha = name)) +
  geom_line() +
  geom_point(size = 0.9, alpha = 0.2) +
  stat_peaks(aes(color = name, 
                 label = paste(..y.label.., ..x.label..)), 
             geom = "text", 
             vjust = -0.5,
             hjust = -0.04,
             span = NULL,
             x.label.fmt = "%d-%m(%b)",
             y.label.fmt = "%.0f pacientes",
             size = 3) +
  scale_color_manual(values = hosp_colors, labels = c("Casos confirmados", 
                                                 "Escenario pesimista (30%)", 
                                                 "Escenario intermedio (45%)",
                                                 "Escenario optimista (60%)",
                                                 "Escenario ajustado (52%)")) +
  scale_alpha_manual(values = hosp_alpha, labels = NULL, guide = "none")  +
  facet_zoom(xlim = c(ymd_hms("2020-04-05 00:00:00"), ymd_hms("2020-05-15 00:00:00")),
             ylim = c(0, 50), zoom.size = 1.2) +
  theme(axis.text.y = element_text(size = 12),
        title = element_text(size = 8, face = "bold", family = "sans"),
        legend.position = "bottom",
        legend.text = element_text(margin = margin(r = 2, unit = "pt"), size = 7),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size = 6)
        ) +
  labs(title = "COVID-19: Población hospitalizada - EPS priorizadas - Modelo SIR - Población susceptible: 767.155",
       subtitle = "Fuente casos confirmados: Puesto de mando unificado - IPS Universitaria (29/04/2020)",
       x = NULL,
       y = NULL,
       color = NULL,
       alpha = NULL) 
#Static
ggsave(plot = hosp_plot, "../plots/tableau_new_sc_hosp_comparison_13-05-2020.png", width = 8, height = 4)

# Data aggregation
hosp_summarized <- hosp_mixed %>% 
  group_by(fecha = tsibble::yearmonth(date)) %>% 
  summarize(ajustado = max(hospS4), pesimista = max(hospS1),
            intermedio = max(hospS2), optimista = max(hospS3))

writexl::write_xlsx(hosp_summarized, "resultados_modelos_hosp_consolidado_mensual.xlsx")
```

### UCE


```{r}
uce_data <- read_csv("../src/uce_data.csv")
new_uce_data <- read_csv("../src/new_uce_data.csv")
## Let's mix it with the hospitalization data for now

ips_uce <- raw_ips %>%
  filter(Resultado...63 == "Positivo",
         tipo_cama == "UCE") %>% 
  mutate(`Fecha consulta` = as_date(`Fecha consulta`)) %>% 
  group_by(`Fecha consulta`, ERP) %>%
  count() %>%
  ungroup()

tidy_uce <- get_mixed(new_uce_data, ips_uce) %>% 
  pivot_longer(cols = c(1:4, "acum"))

uce_colors <- c("acum" = "black", "icuS1" = "darkblue", "icuS2" = "darkorange", "icuS3" = "darkred", "icuS4" = "aquamarine4")
uce_alpha <- c("acum" = 1, "icuS1" = 0.4, "icuS2" = 0.4, "icuS3" = 0.4, "icuS4" = 1)

uce_plot <- tidy_uce %>%
  mutate(date = as_datetime(date)) %>% 
  ggplot(aes(date, value, color = name, alpha = name)) +
  geom_line() +
  geom_point(size = 0.9, alpha = 0.2) +
  stat_peaks(aes(color = name, 
                 label = paste(..y.label.., ..x.label..)), 
             geom = "text", 
             vjust = -0.5,
             hjust = -0.04,
             span = NULL,
             x.label.fmt = "%d-%m(%b)",
             y.label.fmt = "%.0f pacientes",
             size = 3) +
  scale_color_manual(values = uce_colors, labels = c("Casos confirmados", 
                                                 "Escenario pesimista (30%)", 
                                                 "Escenario intermedio (45%)",
                                                 "Escenario optimista (60%)",
                                                 "Escenario ajustado (52%)")) +
  scale_alpha_manual(values = uce_alpha, labels = NULL, guide = "none")  +
  facet_zoom(xlim = c(ymd_hms("2020-04-05 00:00:00"), ymd_hms("2020-05-15 00:00:00")),
             ylim = c(0, 50), zoom.size = 1.2) +
  theme(axis.text.y = element_text(size = 6),
        title = element_text(size = 8, face = "bold", family = "sans"),
        legend.position = "bottom",
        legend.text = element_text(margin = margin(r = 2, unit = "pt"), size = 7),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size = 6)
        ) +
  labs(title = "COVID-19: Población en UCE - EPS priorizadas - Modelo SIR - Población susceptible: 767.155",
       subtitle = "Fuente casos confirmados: Puesto de mando unificado IPS Universitaria (29/04/2020)",
       x = NULL,
       y = NULL,
       color = NULL,
       alpha = NULL)

#Static
ggsave(plot = uce_plot, "../plots/tableau_new_sc_uce_plot_13-05-2020.png", width = 8, height = 4)
```


### UCI

```{r}
uci_data <- read_csv("../src/uci_data.csv")
new_uci_data <- read_csv("../src/new_uci_data.csv")

ips_uci <- raw_ips %>%
  filter(Resultado...63 == "Positivo",
         tipo_cama == "UCI") %>% 
  mutate(`Fecha consulta` = as_date(`Fecha consulta`)) %>% 
  group_by(`Fecha consulta`, ERP) %>%
  count() %>%
  ungroup()

tidy_uci <- get_mixed(new_uci_data , ips_uci) %>%  
  pivot_longer(cols = c(1:4, "acum"))

uci_colors <- c("acum" = "black", "ventS1" = "darkblue", "ventS2" = "darkorange", "ventS3" = "darkred", "ventS4" = "aquamarine4")
uci_alpha <- c("acum" = 1, "ventS1" = 0.4, "ventS2" = 0.4, "ventS3" = 0.4, "ventS4" = 1)

uci_plot <- tidy_uci %>%
  mutate(date = as_datetime(date)) %>% 
  ggplot(aes(date, value, color = name, alpha = name)) +
  geom_line() +
  geom_point(size = 0.9, alpha = 0.2) +
  stat_peaks(aes(color = name, 
                 label = paste(..y.label.., ..x.label..)), 
             geom = "text", 
             vjust = -0.4,
             hjust = -0.04,
             span = NULL,
             x.label.fmt = "%d-%m(%b)",
             y.label.fmt = "%.0f pacientes",
             size = 3) +
  scale_color_manual(values = uci_colors, labels = c("Casos confirmados", 
                                                 "Escenario pesimista (30%)", 
                                                 "Escenario intermedio (45%)",
                                                 "Escenario optimista (60%)",
                                                 "Escenario ajustado (52%)")) +
  scale_alpha_manual(values = uci_alpha, labels = NULL, guide = "none")  +
  facet_zoom(xlim = c(ymd_hms("2020-04-05 00:00:00"), ymd_hms("2020-05-15 00:00:00")),
             ylim = c(0, 50), zoom.size = 1.2) +
  theme(axis.text.y = element_text(size = 6),
        title = element_text(size = 8, face = "bold", family = "sans"),
        legend.position = "bottom",
        legend.text = element_text(margin = margin(r = 2, unit = "pt"), size = 7),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size = 6)
        ) +
  labs(title = "COVID-19: Población en UCI - Modelo SIR - Población susceptible: 767.155",
       subtitle = "Fuente casos confirmados: Puesto de mando unificado - IPS Universitaria (29/04/2020)",
       x = NULL,
       y = NULL,
       color = NULL,
       alpha = NULL)

#Static
ggsave(plot = uci_plot, "../plots/tableau_new_sc_uci_plot_13-05-2020.png", width = 8, height = 4)
```

### Análisis de pacientes negativos vs positivos


         
```{r}
cons <- raw_ips %>% 
  mutate(`Fecha consulta` = as_date(`Fecha consulta`)) %>% 
  group_by(Resultado...63,`Fecha consulta`) %>% 
  count(Resultado...63) %>%
  group_by(Resultado...63) %>% 
  mutate(acum = cumsum(n)) %>% 
  ungroup() %>%
  pivot_longer(cols = c(n, acum)) %>% 
  filter(!is.na(Resultado...63))

cons %>% 
  ggplot(aes(`Fecha consulta`, y = value, color = name)) +
  geom_line() +
  facet_wrap(~Resultado...63) +
  stat_peaks(geom = "text_repel",
             span = NULL,
             aes(label = paste(..y.label..)))

proporcion <- cons %>%
  filter(name == "acum") %>% 
  spread(key = "Resultado...63", value = value) %>% 
  mutate(Positivo = zoo::na.locf(Positivo, fromLast = TRUE),
         proporcion = Negativo/Positivo)


write_xlsx(proporcion, "proporcion_acumulados.xlsx")

proporcion %>% 
  summarize_if(is.numeric, ~mean(.))

```
         
         
## Doubling time análisis

```{r}
doubling_data <- read_csv("../src/doubling-time-of-covid-cases.csv") %>% 
  mutate(Date = mdy(Date)) %>% 
  dplyr::rename("doubling_3days" =`Doubling days of total confirmed cases (3 day period)`)

doubling_col <- doubling_data %>% 
  filter(Entity == "Colombia") %>% 
  mutate(cuarentena = case_when(Date <= ymd("2020-04-13") ~ "sin cuarentena / tomando efectividad",
                                Date >= ymd("2020-05-11") ~ "algunos sectores activados",
                                TRUE ~ "con cuarentena"))

doubling_plot <- doubling_col %>% 
  ggplot(aes(Date, doubling_3days, color = factor(cuarentena))) +
  geom_line() +
  geom_point() +
  geom_vline(xintercept = ymd("2020-03-24")) +
  labs(title = "COVID-19 Datos reales del doubling time en Colombia - Análisis IPS Universitaria",
       subtitle = "Fuente: INS a través de JHU, actualizado (18/05/2020)",
       y = "Doubling time de casos confirmados (periodo 3 días)") +
    theme(axis.text.y = element_text(size = 6),
        title = element_text(size = 8, face = "bold", family = "sans"),
        legend.position = "bottom",
        legend.text = element_text(margin = margin(r = 2, unit = "pt"), size = 7),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size = 6)
        )

ggsave(plot = doubling_plot, "../plots/doubling_plot_18-05-2020.png", width = 8, height = 4)

doubling_col %>% 
  filter(Date < ymd("2020-04-13")) %>% 
  summarize(mean(doubling_3days))
```

